server:
  port: 9001
spring:
  application:
    name: USER-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
  config:
    import: configserver:http://localhost:9296
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
